---
- name: Install Cluster Base Software
  yum: name={{ item }}
       state=present
  with_items:
     - pacemaker
     - corosync
     - pcs
     - cman
     - resource-agents
  tags: [install, base]

- name: Enable pcsd daemon at boot time and start it
  service: name=pcsd
           enabled=yes
           state=started
  tags: [install, base]

- name: Disable Cosorync daemon at boot time and stop it
  service: name=corosync
           enabled=no
           state=stopped
  tags: [install, base]
