---
### Cluster Initialization
- name: Setup cluster user {{ cluster_password }}
  shell: echo "{{ cluster_password }}" | passwd --stdin hacluster
  tags: [install, init]

  # http://adamj.eu/tech/2014/10/02/merging-groups-and-hostvars-in-ansible-variables/
  # https://github.com/wefner/ansible-vagrant/blob/fix/httpd-cluster/adv/code/roles/clustering/tasks/main.yml
- name: Cluster nodes list
  debug:
    msg: |
      {% set space = joiner(" ") %}
      {% for item in [groups['cluster']][0] -%}
        {{ space() }}{{ item }}
      {%- endfor %}
  run_once: true
  register: cluster_nodes_list
  tags: [install, init]

- name: Set nodes list as a fact
  set_fact: cluster_nodes="{{ cluster_nodes_list.msg }}"
  tags: [configuration, cluster]

- name: Auth nodes
  shell: "pcs cluster auth {{ cluster_nodes }} -u hacluster -p {{ cluster_password }}"
  run_once: true
  tags: [install, init]

- name: Create cluster {{ cluster_name }}
  shell: pcs cluster setup --name {{ cluster_name }} {{ cluster_nodes }}
  run_once: True
  tags: [install, init]

- name: Enable cluster services at boot time
  shell: pcs cluster enable --all
  run_once: True
  tags: [install, init]

- name: start cluster sertvices on all nodes
  shell: pcs cluster start --all
  run_once: True
  tags: [install, init]



## Optional
- name: Disable STONITH
  shell: pcs property set stonith-enabled=false
  run_once: True
  when: disable_stonith
  tags: [install, init]

- name: Disable Quorum
  shell: pcs property set no-quorum-policy=ignore
  run_once: True
  when: disable_quorum
  tags: [install, init]
