---

### Install Redis software
- name: Install redis RPM
  yum: name={{ item }}
       state=present
  with_items:
     - redis
  tags: [install, redis]

- name: Disable old/default redis from boot process
  service:  name=redis
            enabled=no
            state=stopped
  when: disable_old_redis
  ignore_errors: yes
  tags: [install, redis]

- name: Deploy OCF agent
  copy: src=redis-ocf-agent
        dest=/usr/lib/ocf/resource.d/heartbeat/redis
        owner=root
        group=root
  tags: [install, redis, config]
